export enum ERROR_CODE {
  // common errors
  APP_MISSING_HEADER = 0,
  APP_MISSING_APP_NAME_OR_DB,
  APP_INVALID,
  INTERNAL_SERVER_ERROR,
  MISSING_PARAM,
  INVALID_PARAM,
  EMPTY_REQUEST,
  INVALID_CODE,

  // Auth errors
  UNAUTHORIZED = 100,
  UNAUTHENTICATED,
  FORBIDDEN,
  VALIDATION_FAILED,
  VERIFICATION_FAILED,
  EMAIL_EXISTS,
  EMAIL_NOT_REGISTERED,
  INVALID_PASSWORD,
  ACCOUNT_NOT_SECURE,
  EXPIRED_TOKEN,

  //
}
